# Generated by Django 2.2.1 on 2019-06-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'job',
                'ordering': ('-sequence',),
            },
        ),
    ]
